export const singleRootTree = [
    {
        team_id: 1,
        team_name: "Aaa",
        parent_team_id: null,
        metadata: { department: "Dep-a" },
        level: 1,
        member_id: 1,
        member_name: "User A",
        member_avatar_url: "http://example.com",
        active: true,
        role_name: "Role XXX",
    },
    {
        team_id: 2,
        team_name: "Bbb",
        parent_team_id: 1,
        metadata: { department: "Dep-b" },
        level: 2,
        member_id: 2,
        member_name: "User B",
        member_avatar_url: "http://example.com",
        active: true,
        role_name: "Role YYY",
    },
    {
        team_id: 3,
        team_name: "Ccc",
        parent_team_id: 2,
        metadata: { department: "Dep-c" },
        level: 3,
        member_id: 3,
        member_name: "User C",
        member_avatar_url: "http://example.com",
        active: true,
        role_name: "Role ZZZ",
    },
];

export const multiRootTree = [
    {
        team_id: 1,
        team_name: "Aaa",
        parent_team_id: null,
        metadata: { department: "Dep-a" },
        level: 1,
        member_id: 1,
        member_name: "User A",
        member_avatar_url: "http://example.com",
        active: true,
        role_name: "Role XXX",
    },
    {
        team_id: 2,
        team_name: "Bbb",
        parent_team_id: null,
        metadata: { department: "Dep-b" },
        level: 1,
        member_id: 2,
        member_name: "User B",
        member_avatar_url: "http://example.com",
        active: true,
        role_name: "Role YYY",
    },
    {
        team_id: 3,
        team_name: "Ccc",
        parent_team_id: null,
        metadata: { department: "Dep-c" },
        level: 1,
        member_id: 3,
        member_name: "User C",
        member_avatar_url: "http://example.com",
        active: true,
        role_name: "Role ZZZ",
    },
];
